<?php

    $body = "       <div id=\"container\">";
    $body .= "          <div class=\"board\" id=\"main-board\">";
    $body .= "              <!-- board blocks generated by createBoard() in script.js -->";
    $body .= "          </div>";

    $body .= "          <div id=\"info-container\">";
    $body .= "              <div id=\"up-next-board\">";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "              </div>";
    $body .= "              <div>";
    $body .= "                  <p id=\"p-museo-moderno\">Up Next</p>";
    $body .= "              </div>";
    $body .= "              <div id=\"btn-container\">";
    $body .= "                  <div id=\"score-container\">";
    $body .= "                      <h3 id=\"h3-score\">Score <span id=\"score\">0</span></h3>";
    $body .= "                  </div>";
    $body .= "                  <div id=\"start-btn-container\">";
    $body .= "                      <button id=\"start-btn\">START/PAUSE</button>";
    $body .= "                  </div>";
    $body .= "                  <div id=\"credit-container\">";
    $body .= "                      <p id=\"p-indie-flower\">Built by Won R.</p>";
    $body .= "                   </div>";
    $body .= "              </div>";
    $body .= "          </div>";
    $body .= "      </div>";

?>