<?php

    $body = "       <div class=\"et-main-container\" id=\"et-main-container-0\">";
    $body .= "          <div class=\"game-board\" id=\"game-board-0\">";
    $body .= "              <!-- board blocks generated by createBoard() in script.js -->";
    $body .= "          </div>";

    $body .= "          <div class=\"et-info-container\" id=\"et-info-container-0\">";
    $body .= "              <div class=\"mini-board\" id=\"mini-board-0\">";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "                  <div class=\"board-block\"></div>";
    $body .= "              </div>";
    $body .= "              <h4 class=\"h4-museo-moderno\" id=\"h4-museo-moderno-0\">Up Next</h4>";
    $body .= "              <div class=\"score-n-btn-container\" id=\"score-n-btn-container-0\">";
    $body .= "                  <div class=\"score-container\" id=\"score-container-0\">";
    $body .= "                      <h3 class=\"h3-score-text\" id=\"h3-score-text-0\">Score</h3>";
	$body .= "						<span class=\"score-value\" id=\"score-value-0\">0</span>";
    $body .= "                  </div>";
    $body .= "                  <button type=\"button\" class=\"game-btn\" id=\"pause-resume-btn\">PAUSE/RESUME</button>";
    $body .= "                  <button type=\"button\" class=\"game-btn\" id=\"start-new-btn\">START NEW GAME</button>";
    $body .= "                  <p class=\"p-museo-moderno\"  id=\"p-museo-moderno-1\">Built by Won R.</p>";
    $body .= "              </div>";
    $body .= "          </div>";
    $body .= "      </div>";

?>
